### ISSUE TITLE
Buffer Distance Restriction

### ISSUE THREAD

**Issue by SamDrummond** [WaimakaririGeospatial/SpatialQueryWidget#3]
The buffer distance parameter only allows a user to select a number between 1 & 100. 

Steps to create

1. Open the Spatial Query Widget
2. Choose a layer
3. Type 101 in the buffer distance counter

![image](https://cloud.githubusercontent.com/assets/4656969/8664473/c77011f2-2a2b-11e5-9241-a9390466a672.png)

**Comment by Lizmgbs** [comment]
Hey Sam what do you need the parameter to be?

**Comment by SamDrummond** [comment]
I think it would make sense for it not to be restricted. Users should be able to add any unit to a value more than 100. Obviously this means that they would be able to put stupid values in but I think this is preferable to letting them put in 100m but then 0.2km if they wanted to buffer 200m.
